# Generated by Django 3.2.5 on 2021-07-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question_bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, verbose_name='创建时间')),
                ('classname', models.CharField(max_length=255, verbose_name='分类')),
                ('question', models.CharField(max_length=255, verbose_name='题目')),
                ('answer', models.CharField(blank=True, max_length=255, null=True, verbose_name='答案')),
                ('option', models.CharField(max_length=255, verbose_name='选项')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, verbose_name='创建时间')),
                ('classname', models.CharField(max_length=255, verbose_name='分类')),
                ('id_card', models.CharField(max_length=255, verbose_name='身份证')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='姓名')),
                ('icon', models.CharField(blank=True, max_length=255, null=True, verbose_name='头像')),
                ('userid', models.CharField(blank=True, max_length=255, null=True, verbose_name='userId')),
            ],
        ),
    ]
