# Generated by Django 3.2.5 on 2021-07-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccenpx', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question_bank',
            options={'verbose_name_plural': '题库'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '用户表'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='icon',
            new_name='icon_url',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(default=0, null=True, verbose_name='当前状态'),
        ),
    ]
