# Generated by Django 3.2.5 on 2021-07-21 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccenpx', '0002_auto_20210721_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cdkey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, verbose_name='创建时间')),
                ('cdk', models.CharField(max_length=255, verbose_name='分类')),
                ('status', models.IntegerField(default=0, null=True, verbose_name='当前状态')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ccenpx.user', verbose_name='身份证')),
            ],
            options={
                'verbose_name_plural': '卡密表',
            },
        ),
    ]
