# Generated by Django 3.2.5 on 2021-07-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccenpx', '0005_auto_20210722_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_bank',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
    ]
