# Generated by Django 3.2.5 on 2021-07-22 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccenpx', '0007_alter_question_bank_create_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_bank',
            name='create_time',
        ),
    ]
