# Generated by Django 3.2.5 on 2021-07-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccenpx', '0008_remove_question_bank_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上次操作时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(-2, '正在排队'), (-1, '异常'), (0, '未开始'), (1, '正在考试'), (2, '已交卷')], default=0, null=True, verbose_name='当前状态'),
        ),
    ]
